# Assignment_1(Numpy Fundamentals) Q2 
    Muhammad Saad Khan

1. Import the numpy package under the name np

In [6]:
import numpy as np


2. Create a null vector of size 10 

In [10]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [11]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [12]:
np.size(a)

40

5. Print the type of the previous array in question 3

In [13]:
type(a)

numpy.ndarray

6. Print the numpy version and the configuration

7. Print the dimension of the array in question 3

In [14]:
a.ndim

1

8. Create a boolean array with all the True values

In [17]:
np.ones(20, dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

9. Create a two dimensional array

In [18]:
b = np.array ([[1,2,3,4,5,6] , [10,11,12,13,14,15]])
b

array([[ 1,  2,  3,  4,  5,  6],
       [10, 11, 12, 13, 14, 15]])

10. Create a three dimensional array

In [23]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

11. Reverse a vector (first element becomes last)

In [29]:
arr = [2,1,4,5]
arr.reverse()
arr

[5, 4, 1, 2]

In [31]:
arr_1  = [1,10,11,8]
d = arr_1[::-1]
d

[8, 11, 10, 1]

12. Create a null vector of size 10 but the fifth value which is 1 

In [35]:
y = np.zeros(10)
y[5] = 1
y

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [38]:
z = np.identity(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [45]:
int_arr = np.array([1,2,3,4,5])
float_arr = int_arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2

In [46]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3 = arr1 * arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [47]:
arr4 = arr1 == arr2
arr4.all()
arr4

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [58]:
arr5 = np.arange(10)
arr5[arr5 % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [57]:
arr5[arr5 % 2 == 1] = -1
arr5

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [59]:
arr6 = np.arange(10)
arr6[5:9] = 12
arr6

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside